# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/effect/v1/effect.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cerbos/effect/v1/effect.proto", :syntax => :proto3) do
    add_enum "cerbos.effect.v1.Effect" do
      value :EFFECT_UNSPECIFIED, 0
      value :EFFECT_ALLOW, 1
      value :EFFECT_DENY, 2
      value :EFFECT_NO_MATCH, 3
    end
  end
end

module Cerbos::Protobuf::Cerbos
  module Effect
    module V1
      Effect = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.effect.v1.Effect").enummodule
    end
  end
end
