# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cerbos/cloud/store/v1/store.proto for package 'cerbos.cloud.store.v1'
# Original file comments:
# Copyright 2021-2025 Zenauth Ltd.
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'cerbos/protobuf/cerbos/cloud/store/v1/store_pb'

module Cerbos::Protobuf::Cerbos
  module Cloud
    module Store
      module V1
        module CerbosStoreService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'cerbos.cloud.store.v1.CerbosStoreService'

            rpc :ListFiles, ::Cerbos::Protobuf::Cerbos::Cloud::Store::V1::ListFilesRequest, ::Cerbos::Protobuf::Cerbos::Cloud::Store::V1::ListFilesResponse
            rpc :GetFiles, ::Cerbos::Protobuf::Cerbos::Cloud::Store::V1::GetFilesRequest, ::Cerbos::Protobuf::Cerbos::Cloud::Store::V1::GetFilesResponse
            rpc :ModifyFiles, ::Cerbos::Protobuf::Cerbos::Cloud::Store::V1::ModifyFilesRequest, ::Cerbos::Protobuf::Cerbos::Cloud::Store::V1::ModifyFilesResponse
            rpc :ReplaceFiles, ::Cerbos::Protobuf::Cerbos::Cloud::Store::V1::ReplaceFilesRequest, ::Cerbos::Protobuf::Cerbos::Cloud::Store::V1::ReplaceFilesResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
