inherit_mode:
  merge:
    - Exclude

require:
  - standard

plugins:
  - rubocop-rake
  - rubocop-rspec
  - standard-custom
  - standard-performance

inherit_gem:
  standard: config/ruby-3.1.yml

AllCops:
  Exclude:
    - bin/bundle
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - bin/yard
    - lib/cerbos/protobuf/**/*
  NewCops: enable

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
