# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/response/v1/response.proto

require 'google/protobuf'

require 'cerbos/protobuf/cerbos/effect/v1/effect_pb'
require 'cerbos/protobuf/cerbos/engine/v1/engine_pb'
require 'cerbos/protobuf/cerbos/schema/v1/schema_pb'
require 'cerbos/protobuf/protoc-gen-openapiv2/options/annotations_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cerbos/response/v1/response.proto", :syntax => :proto3) do
    add_message "cerbos.response.v1.PlanResourcesResponse" do
      optional :request_id, :string, 1, json_name: "requestId"
      optional :action, :string, 2, json_name: "action"
      optional :resource_kind, :string, 3, json_name: "resourceKind"
      optional :policy_version, :string, 4, json_name: "policyVersion"
      optional :filter, :message, 5, "cerbos.engine.v1.PlanResourcesFilter", json_name: "filter"
      optional :meta, :message, 6, "cerbos.response.v1.PlanResourcesResponse.Meta", json_name: "meta"
      repeated :validation_errors, :message, 7, "cerbos.schema.v1.ValidationError", json_name: "validationErrors"
    end
    add_message "cerbos.response.v1.PlanResourcesResponse.Meta" do
      optional :filter_debug, :string, 1, json_name: "filterDebug"
      optional :matched_scope, :string, 2, json_name: "matchedScope"
    end
    add_message "cerbos.response.v1.CheckResourceSetResponse" do
      optional :request_id, :string, 1, json_name: "requestId"
      map :resource_instances, :string, :message, 2, "cerbos.response.v1.CheckResourceSetResponse.ActionEffectMap"
      optional :meta, :message, 3, "cerbos.response.v1.CheckResourceSetResponse.Meta", json_name: "meta"
    end
    add_message "cerbos.response.v1.CheckResourceSetResponse.ActionEffectMap" do
      map :actions, :string, :enum, 1, "cerbos.effect.v1.Effect"
      repeated :validation_errors, :message, 2, "cerbos.schema.v1.ValidationError", json_name: "validationErrors"
    end
    add_message "cerbos.response.v1.CheckResourceSetResponse.Meta" do
      map :resource_instances, :string, :message, 1, "cerbos.response.v1.CheckResourceSetResponse.Meta.ActionMeta"
    end
    add_message "cerbos.response.v1.CheckResourceSetResponse.Meta.EffectMeta" do
      optional :matched_policy, :string, 1, json_name: "matchedPolicy"
      optional :matched_scope, :string, 2, json_name: "matchedScope"
    end
    add_message "cerbos.response.v1.CheckResourceSetResponse.Meta.ActionMeta" do
      map :actions, :string, :message, 1, "cerbos.response.v1.CheckResourceSetResponse.Meta.EffectMeta"
      repeated :effective_derived_roles, :string, 2, json_name: "effectiveDerivedRoles"
    end
    add_message "cerbos.response.v1.CheckResourceBatchResponse" do
      optional :request_id, :string, 1, json_name: "requestId"
      repeated :results, :message, 2, "cerbos.response.v1.CheckResourceBatchResponse.ActionEffectMap", json_name: "results"
    end
    add_message "cerbos.response.v1.CheckResourceBatchResponse.ActionEffectMap" do
      optional :resource_id, :string, 1, json_name: "resourceId"
      map :actions, :string, :enum, 2, "cerbos.effect.v1.Effect"
      repeated :validation_errors, :message, 3, "cerbos.schema.v1.ValidationError", json_name: "validationErrors"
    end
    add_message "cerbos.response.v1.CheckResourcesResponse" do
      optional :request_id, :string, 1, json_name: "requestId"
      repeated :results, :message, 2, "cerbos.response.v1.CheckResourcesResponse.ResultEntry", json_name: "results"
    end
    add_message "cerbos.response.v1.CheckResourcesResponse.ResultEntry" do
      optional :resource, :message, 1, "cerbos.response.v1.CheckResourcesResponse.ResultEntry.Resource", json_name: "resource"
      map :actions, :string, :enum, 2, "cerbos.effect.v1.Effect"
      repeated :validation_errors, :message, 3, "cerbos.schema.v1.ValidationError", json_name: "validationErrors"
      optional :meta, :message, 4, "cerbos.response.v1.CheckResourcesResponse.ResultEntry.Meta", json_name: "meta"
    end
    add_message "cerbos.response.v1.CheckResourcesResponse.ResultEntry.Resource" do
      optional :id, :string, 1, json_name: "id"
      optional :kind, :string, 2, json_name: "kind"
      optional :policy_version, :string, 3, json_name: "policyVersion"
      optional :scope, :string, 4, json_name: "scope"
    end
    add_message "cerbos.response.v1.CheckResourcesResponse.ResultEntry.Meta" do
      map :actions, :string, :message, 1, "cerbos.response.v1.CheckResourcesResponse.ResultEntry.Meta.EffectMeta"
      repeated :effective_derived_roles, :string, 2, json_name: "effectiveDerivedRoles"
    end
    add_message "cerbos.response.v1.CheckResourcesResponse.ResultEntry.Meta.EffectMeta" do
      optional :matched_policy, :string, 1, json_name: "matchedPolicy"
      optional :matched_scope, :string, 2, json_name: "matchedScope"
    end
    add_message "cerbos.response.v1.ServerInfoResponse" do
      optional :version, :string, 1, json_name: "version"
      optional :commit, :string, 2, json_name: "commit"
      optional :build_date, :string, 3, json_name: "buildDate"
    end
  end
end

module Cerbos::Protobuf::Cerbos
  module Response
    module V1
      PlanResourcesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.PlanResourcesResponse").msgclass
      PlanResourcesResponse::Meta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.PlanResourcesResponse.Meta").msgclass
      CheckResourceSetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourceSetResponse").msgclass
      CheckResourceSetResponse::ActionEffectMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourceSetResponse.ActionEffectMap").msgclass
      CheckResourceSetResponse::Meta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourceSetResponse.Meta").msgclass
      CheckResourceSetResponse::Meta::EffectMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourceSetResponse.Meta.EffectMeta").msgclass
      CheckResourceSetResponse::Meta::ActionMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourceSetResponse.Meta.ActionMeta").msgclass
      CheckResourceBatchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourceBatchResponse").msgclass
      CheckResourceBatchResponse::ActionEffectMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourceBatchResponse.ActionEffectMap").msgclass
      CheckResourcesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourcesResponse").msgclass
      CheckResourcesResponse::ResultEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourcesResponse.ResultEntry").msgclass
      CheckResourcesResponse::ResultEntry::Resource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourcesResponse.ResultEntry.Resource").msgclass
      CheckResourcesResponse::ResultEntry::Meta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourcesResponse.ResultEntry.Meta").msgclass
      CheckResourcesResponse::ResultEntry::Meta::EffectMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.CheckResourcesResponse.ResultEntry.Meta.EffectMeta").msgclass
      ServerInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.response.v1.ServerInfoResponse").msgclass
    end
  end
end
