name: cerbos-sdk-ruby-test

services:
  plaintext:
    image: ghcr.io/cerbos/cerbos:${CERBOS_IMAGE_TAG:-$CERBOS_VERSION}
    environment:
      - CERBOS_CONFIG=/config/plaintext.yaml
    healthcheck:
      interval: 2s
    ports:
      - 3593
    user: ${USER}
    volumes:
      - type: bind
        source: config/cerbos
        target: /config
        read_only: true
      - type: bind
        source: policies/${POLICIES_VERSION}
        target: /policies
        read_only: true

  socket:
    profiles:
      - linux
    extends: plaintext
    environment:
      - CERBOS_CONFIG=/config/socket.yaml
    volumes:
      - type: bind
        source: ../../tmp/socket
        target: /socket

  tls:
    extends: plaintext
    environment:
      - CERBOS_CONFIG=/config/tls.yaml
    volumes:
      - type: bind
        source: ../../tmp/certificates
        target: /certificates
        read_only: true

  mtls:
    image: traefik:2.10
    command:
      - --entrypoints.grpc.address=:3593
      - --ping
      - --providers.file.filename=/config/mtls.yaml
    healthcheck:
      interval: 2s
      timeout: 1s
      test:
        - CMD
        - traefik
        - healthcheck
        - --ping
    ports:
      - 3593
    volumes:
      - type: bind
        source: ../../tmp/certificates
        target: /certificates
        read_only: true
      - type: bind
        source: config/traefik
        target: /config
        read_only: true
