# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/request/v1/request.proto

require 'google/protobuf'

require 'cerbos/protobuf/cerbos/engine/v1/engine_pb'
require 'cerbos/protobuf/google/api/field_behavior_pb'
require 'google/protobuf/struct_pb'
require 'cerbos/protobuf/protoc-gen-openapiv2/options/annotations_pb'
require 'cerbos/protobuf/validate/validate_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cerbos/request/v1/request.proto", :syntax => :proto3) do
    add_message "cerbos.request.v1.PlanResourcesRequest" do
      optional :request_id, :string, 1, json_name: "requestId"
      optional :action, :string, 2, json_name: "action"
      optional :principal, :message, 3, "cerbos.engine.v1.Principal", json_name: "principal"
      optional :resource, :message, 4, "cerbos.engine.v1.PlanResourcesInput.Resource", json_name: "resource"
      optional :aux_data, :message, 5, "cerbos.request.v1.AuxData", json_name: "auxData"
      optional :include_meta, :bool, 6, json_name: "includeMeta"
    end
    add_message "cerbos.request.v1.CheckResourceSetRequest" do
      optional :request_id, :string, 1, json_name: "requestId"
      repeated :actions, :string, 2, json_name: "actions"
      optional :principal, :message, 3, "cerbos.engine.v1.Principal", json_name: "principal"
      optional :resource, :message, 4, "cerbos.request.v1.ResourceSet", json_name: "resource"
      optional :include_meta, :bool, 5, json_name: "includeMeta"
      optional :aux_data, :message, 6, "cerbos.request.v1.AuxData", json_name: "auxData"
    end
    add_message "cerbos.request.v1.ResourceSet" do
      optional :kind, :string, 1, json_name: "kind"
      optional :policy_version, :string, 2, json_name: "policyVersion"
      map :instances, :string, :message, 3, "cerbos.request.v1.AttributesMap"
      optional :scope, :string, 4, json_name: "scope"
    end
    add_message "cerbos.request.v1.AttributesMap" do
      map :attr, :string, :message, 1, "google.protobuf.Value"
    end
    add_message "cerbos.request.v1.CheckResourceBatchRequest" do
      optional :request_id, :string, 1, json_name: "requestId"
      optional :principal, :message, 2, "cerbos.engine.v1.Principal", json_name: "principal"
      repeated :resources, :message, 3, "cerbos.request.v1.CheckResourceBatchRequest.BatchEntry", json_name: "resources"
      optional :aux_data, :message, 4, "cerbos.request.v1.AuxData", json_name: "auxData"
    end
    add_message "cerbos.request.v1.CheckResourceBatchRequest.BatchEntry" do
      repeated :actions, :string, 1, json_name: "actions"
      optional :resource, :message, 2, "cerbos.engine.v1.Resource", json_name: "resource"
    end
    add_message "cerbos.request.v1.CheckResourcesRequest" do
      optional :request_id, :string, 1, json_name: "requestId"
      optional :include_meta, :bool, 2, json_name: "includeMeta"
      optional :principal, :message, 3, "cerbos.engine.v1.Principal", json_name: "principal"
      repeated :resources, :message, 4, "cerbos.request.v1.CheckResourcesRequest.ResourceEntry", json_name: "resources"
      optional :aux_data, :message, 5, "cerbos.request.v1.AuxData", json_name: "auxData"
    end
    add_message "cerbos.request.v1.CheckResourcesRequest.ResourceEntry" do
      repeated :actions, :string, 1, json_name: "actions"
      optional :resource, :message, 2, "cerbos.engine.v1.Resource", json_name: "resource"
    end
    add_message "cerbos.request.v1.AuxData" do
      optional :jwt, :message, 1, "cerbos.request.v1.AuxData.JWT", json_name: "jwt"
    end
    add_message "cerbos.request.v1.AuxData.JWT" do
      optional :token, :string, 1, json_name: "token"
      optional :key_set_id, :string, 2, json_name: "keySetId"
    end
    add_message "cerbos.request.v1.ServerInfoRequest" do
    end
  end
end

module Cerbos::Protobuf::Cerbos
  module Request
    module V1
      PlanResourcesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.PlanResourcesRequest").msgclass
      CheckResourceSetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.CheckResourceSetRequest").msgclass
      ResourceSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.ResourceSet").msgclass
      AttributesMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.AttributesMap").msgclass
      CheckResourceBatchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.CheckResourceBatchRequest").msgclass
      CheckResourceBatchRequest::BatchEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.CheckResourceBatchRequest.BatchEntry").msgclass
      CheckResourcesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.CheckResourcesRequest").msgclass
      CheckResourcesRequest::ResourceEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.CheckResourcesRequest.ResourceEntry").msgclass
      AuxData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.AuxData").msgclass
      AuxData::JWT = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.AuxData.JWT").msgclass
      ServerInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.request.v1.ServerInfoRequest").msgclass
    end
  end
end
