# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-openapiv2/options/annotations.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'
require 'cerbos/protobuf/protoc-gen-openapiv2/options/openapiv2_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protoc-gen-openapiv2/options/annotations.proto", :syntax => :proto3) do
  end
end

module Cerbos::Protobuf::Grpc
  module Gateway
    module ProtocGenOpenapiv2
      module Options
      end
    end
  end
end
