# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-openapiv2/options/openapiv2.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protoc-gen-openapiv2/options/openapiv2.proto", :syntax => :proto3) do
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Swagger" do
      optional :swagger, :string, 1, json_name: "swagger"
      optional :info, :message, 2, "grpc.gateway.protoc_gen_openapiv2.options.Info", json_name: "info"
      optional :host, :string, 3, json_name: "host"
      optional :base_path, :string, 4, json_name: "basePath"
      repeated :schemes, :enum, 5, "grpc.gateway.protoc_gen_openapiv2.options.Scheme", json_name: "schemes"
      repeated :consumes, :string, 6, json_name: "consumes"
      repeated :produces, :string, 7, json_name: "produces"
      map :responses, :string, :message, 10, "grpc.gateway.protoc_gen_openapiv2.options.Response"
      optional :security_definitions, :message, 11, "grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitions", json_name: "securityDefinitions"
      repeated :security, :message, 12, "grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement", json_name: "security"
      optional :external_docs, :message, 14, "grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation", json_name: "externalDocs"
      map :extensions, :string, :message, 15, "google.protobuf.Value"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Operation" do
      repeated :tags, :string, 1, json_name: "tags"
      optional :summary, :string, 2, json_name: "summary"
      optional :description, :string, 3, json_name: "description"
      optional :external_docs, :message, 4, "grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation", json_name: "externalDocs"
      optional :operation_id, :string, 5, json_name: "operationId"
      repeated :consumes, :string, 6, json_name: "consumes"
      repeated :produces, :string, 7, json_name: "produces"
      map :responses, :string, :message, 9, "grpc.gateway.protoc_gen_openapiv2.options.Response"
      repeated :schemes, :enum, 10, "grpc.gateway.protoc_gen_openapiv2.options.Scheme", json_name: "schemes"
      optional :deprecated, :bool, 11, json_name: "deprecated"
      repeated :security, :message, 12, "grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement", json_name: "security"
      map :extensions, :string, :message, 13, "google.protobuf.Value"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Header" do
      optional :description, :string, 1, json_name: "description"
      optional :type, :string, 2, json_name: "type"
      optional :format, :string, 3, json_name: "format"
      optional :default, :string, 6, json_name: "default"
      optional :pattern, :string, 13, json_name: "pattern"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Response" do
      optional :description, :string, 1, json_name: "description"
      optional :schema, :message, 2, "grpc.gateway.protoc_gen_openapiv2.options.Schema", json_name: "schema"
      map :headers, :string, :message, 3, "grpc.gateway.protoc_gen_openapiv2.options.Header"
      map :examples, :string, :string, 4
      map :extensions, :string, :message, 5, "google.protobuf.Value"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Info" do
      optional :title, :string, 1, json_name: "title"
      optional :description, :string, 2, json_name: "description"
      optional :terms_of_service, :string, 3, json_name: "termsOfService"
      optional :contact, :message, 4, "grpc.gateway.protoc_gen_openapiv2.options.Contact", json_name: "contact"
      optional :license, :message, 5, "grpc.gateway.protoc_gen_openapiv2.options.License", json_name: "license"
      optional :version, :string, 6, json_name: "version"
      map :extensions, :string, :message, 7, "google.protobuf.Value"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Contact" do
      optional :name, :string, 1, json_name: "name"
      optional :url, :string, 2, json_name: "url"
      optional :email, :string, 3, json_name: "email"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.License" do
      optional :name, :string, 1, json_name: "name"
      optional :url, :string, 2, json_name: "url"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation" do
      optional :description, :string, 1, json_name: "description"
      optional :url, :string, 2, json_name: "url"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Schema" do
      optional :json_schema, :message, 1, "grpc.gateway.protoc_gen_openapiv2.options.JSONSchema", json_name: "jsonSchema"
      optional :discriminator, :string, 2, json_name: "discriminator"
      optional :read_only, :bool, 3, json_name: "readOnly"
      optional :external_docs, :message, 5, "grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation", json_name: "externalDocs"
      optional :example, :string, 6, json_name: "example"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.JSONSchema" do
      optional :ref, :string, 3, json_name: "ref"
      optional :title, :string, 5, json_name: "title"
      optional :description, :string, 6, json_name: "description"
      optional :default, :string, 7, json_name: "default"
      optional :read_only, :bool, 8, json_name: "readOnly"
      optional :example, :string, 9, json_name: "example"
      optional :multiple_of, :double, 10, json_name: "multipleOf"
      optional :maximum, :double, 11, json_name: "maximum"
      optional :exclusive_maximum, :bool, 12, json_name: "exclusiveMaximum"
      optional :minimum, :double, 13, json_name: "minimum"
      optional :exclusive_minimum, :bool, 14, json_name: "exclusiveMinimum"
      optional :max_length, :uint64, 15, json_name: "maxLength"
      optional :min_length, :uint64, 16, json_name: "minLength"
      optional :pattern, :string, 17, json_name: "pattern"
      optional :max_items, :uint64, 20, json_name: "maxItems"
      optional :min_items, :uint64, 21, json_name: "minItems"
      optional :unique_items, :bool, 22, json_name: "uniqueItems"
      optional :max_properties, :uint64, 24, json_name: "maxProperties"
      optional :min_properties, :uint64, 25, json_name: "minProperties"
      repeated :required, :string, 26, json_name: "required"
      repeated :array, :string, 34, json_name: "array"
      repeated :type, :enum, 35, "grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes", json_name: "type"
      optional :format, :string, 36, json_name: "format"
      repeated :enum, :string, 46, json_name: "enum"
      optional :field_configuration, :message, 1001, "grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.FieldConfiguration", json_name: "fieldConfiguration"
      map :extensions, :string, :message, 48, "google.protobuf.Value"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.FieldConfiguration" do
      optional :path_param_name, :string, 47, json_name: "pathParamName"
    end
    add_enum "grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes" do
      value :UNKNOWN, 0
      value :ARRAY, 1
      value :BOOLEAN, 2
      value :INTEGER, 3
      value :NULL, 4
      value :NUMBER, 5
      value :OBJECT, 6
      value :STRING, 7
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Tag" do
      optional :description, :string, 2, json_name: "description"
      optional :external_docs, :message, 3, "grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation", json_name: "externalDocs"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitions" do
      map :security, :string, :message, 1, "grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme" do
      optional :type, :enum, 1, "grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Type", json_name: "type"
      optional :description, :string, 2, json_name: "description"
      optional :name, :string, 3, json_name: "name"
      optional :in, :enum, 4, "grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.In", json_name: "in"
      optional :flow, :enum, 5, "grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Flow", json_name: "flow"
      optional :authorization_url, :string, 6, json_name: "authorizationUrl"
      optional :token_url, :string, 7, json_name: "tokenUrl"
      optional :scopes, :message, 8, "grpc.gateway.protoc_gen_openapiv2.options.Scopes", json_name: "scopes"
      map :extensions, :string, :message, 9, "google.protobuf.Value"
    end
    add_enum "grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Type" do
      value :TYPE_INVALID, 0
      value :TYPE_BASIC, 1
      value :TYPE_API_KEY, 2
      value :TYPE_OAUTH2, 3
    end
    add_enum "grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.In" do
      value :IN_INVALID, 0
      value :IN_QUERY, 1
      value :IN_HEADER, 2
    end
    add_enum "grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Flow" do
      value :FLOW_INVALID, 0
      value :FLOW_IMPLICIT, 1
      value :FLOW_PASSWORD, 2
      value :FLOW_APPLICATION, 3
      value :FLOW_ACCESS_CODE, 4
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement" do
      map :security_requirement, :string, :message, 1, "grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement.SecurityRequirementValue"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement.SecurityRequirementValue" do
      repeated :scope, :string, 1, json_name: "scope"
    end
    add_message "grpc.gateway.protoc_gen_openapiv2.options.Scopes" do
      map :scope, :string, :string, 1
    end
    add_enum "grpc.gateway.protoc_gen_openapiv2.options.Scheme" do
      value :UNKNOWN, 0
      value :HTTP, 1
      value :HTTPS, 2
      value :WS, 3
      value :WSS, 4
    end
  end
end

module Cerbos::Protobuf::Grpc
  module Gateway
    module ProtocGenOpenapiv2
      module Options
        Swagger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Swagger").msgclass
        Operation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Operation").msgclass
        Header = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Header").msgclass
        Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Response").msgclass
        Info = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Info").msgclass
        Contact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Contact").msgclass
        License = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.License").msgclass
        ExternalDocumentation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation").msgclass
        Schema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Schema").msgclass
        JSONSchema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.JSONSchema").msgclass
        JSONSchema::FieldConfiguration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.FieldConfiguration").msgclass
        JSONSchema::JSONSchemaSimpleTypes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes").enummodule
        Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Tag").msgclass
        SecurityDefinitions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitions").msgclass
        SecurityScheme = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme").msgclass
        SecurityScheme::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Type").enummodule
        SecurityScheme::In = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.In").enummodule
        SecurityScheme::Flow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Flow").enummodule
        SecurityRequirement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement").msgclass
        SecurityRequirement::SecurityRequirementValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement.SecurityRequirementValue").msgclass
        Scopes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Scopes").msgclass
        Scheme = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.gateway.protoc_gen_openapiv2.options.Scheme").enummodule
      end
    end
  end
end
