# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1alpha1/checked.proto

require 'google/protobuf'

require 'cerbos/protobuf/google/api/expr/v1alpha1/syntax_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/struct_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/api/expr/v1alpha1/checked.proto", :syntax => :proto3) do
    add_message "google.api.expr.v1alpha1.CheckedExpr" do
      map :reference_map, :int64, :message, 2, "google.api.expr.v1alpha1.Reference"
      map :type_map, :int64, :message, 3, "google.api.expr.v1alpha1.Type"
      optional :source_info, :message, 5, "google.api.expr.v1alpha1.SourceInfo", json_name: "sourceInfo"
      optional :expr_version, :string, 6, json_name: "exprVersion"
      optional :expr, :message, 4, "google.api.expr.v1alpha1.Expr", json_name: "expr"
    end
    add_message "google.api.expr.v1alpha1.Type" do
      oneof :type_kind do
        optional :dyn, :message, 1, "google.protobuf.Empty", json_name: "dyn"
        optional :null, :enum, 2, "google.protobuf.NullValue", json_name: "null"
        optional :primitive, :enum, 3, "google.api.expr.v1alpha1.Type.PrimitiveType", json_name: "primitive"
        optional :wrapper, :enum, 4, "google.api.expr.v1alpha1.Type.PrimitiveType", json_name: "wrapper"
        optional :well_known, :enum, 5, "google.api.expr.v1alpha1.Type.WellKnownType", json_name: "wellKnown"
        optional :list_type, :message, 6, "google.api.expr.v1alpha1.Type.ListType", json_name: "listType"
        optional :map_type, :message, 7, "google.api.expr.v1alpha1.Type.MapType", json_name: "mapType"
        optional :function, :message, 8, "google.api.expr.v1alpha1.Type.FunctionType", json_name: "function"
        optional :message_type, :string, 9, json_name: "messageType"
        optional :type_param, :string, 10, json_name: "typeParam"
        optional :type, :message, 11, "google.api.expr.v1alpha1.Type", json_name: "type"
        optional :error, :message, 12, "google.protobuf.Empty", json_name: "error"
        optional :abstract_type, :message, 14, "google.api.expr.v1alpha1.Type.AbstractType", json_name: "abstractType"
      end
    end
    add_message "google.api.expr.v1alpha1.Type.ListType" do
      optional :elem_type, :message, 1, "google.api.expr.v1alpha1.Type", json_name: "elemType"
    end
    add_message "google.api.expr.v1alpha1.Type.MapType" do
      optional :key_type, :message, 1, "google.api.expr.v1alpha1.Type", json_name: "keyType"
      optional :value_type, :message, 2, "google.api.expr.v1alpha1.Type", json_name: "valueType"
    end
    add_message "google.api.expr.v1alpha1.Type.FunctionType" do
      optional :result_type, :message, 1, "google.api.expr.v1alpha1.Type", json_name: "resultType"
      repeated :arg_types, :message, 2, "google.api.expr.v1alpha1.Type", json_name: "argTypes"
    end
    add_message "google.api.expr.v1alpha1.Type.AbstractType" do
      optional :name, :string, 1, json_name: "name"
      repeated :parameter_types, :message, 2, "google.api.expr.v1alpha1.Type", json_name: "parameterTypes"
    end
    add_enum "google.api.expr.v1alpha1.Type.PrimitiveType" do
      value :PRIMITIVE_TYPE_UNSPECIFIED, 0
      value :BOOL, 1
      value :INT64, 2
      value :UINT64, 3
      value :DOUBLE, 4
      value :STRING, 5
      value :BYTES, 6
    end
    add_enum "google.api.expr.v1alpha1.Type.WellKnownType" do
      value :WELL_KNOWN_TYPE_UNSPECIFIED, 0
      value :ANY, 1
      value :TIMESTAMP, 2
      value :DURATION, 3
    end
    add_message "google.api.expr.v1alpha1.Decl" do
      optional :name, :string, 1, json_name: "name"
      oneof :decl_kind do
        optional :ident, :message, 2, "google.api.expr.v1alpha1.Decl.IdentDecl", json_name: "ident"
        optional :function, :message, 3, "google.api.expr.v1alpha1.Decl.FunctionDecl", json_name: "function"
      end
    end
    add_message "google.api.expr.v1alpha1.Decl.IdentDecl" do
      optional :type, :message, 1, "google.api.expr.v1alpha1.Type", json_name: "type"
      optional :value, :message, 2, "google.api.expr.v1alpha1.Constant", json_name: "value"
      optional :doc, :string, 3, json_name: "doc"
    end
    add_message "google.api.expr.v1alpha1.Decl.FunctionDecl" do
      repeated :overloads, :message, 1, "google.api.expr.v1alpha1.Decl.FunctionDecl.Overload", json_name: "overloads"
    end
    add_message "google.api.expr.v1alpha1.Decl.FunctionDecl.Overload" do
      optional :overload_id, :string, 1, json_name: "overloadId"
      repeated :params, :message, 2, "google.api.expr.v1alpha1.Type", json_name: "params"
      repeated :type_params, :string, 3, json_name: "typeParams"
      optional :result_type, :message, 4, "google.api.expr.v1alpha1.Type", json_name: "resultType"
      optional :is_instance_function, :bool, 5, json_name: "isInstanceFunction"
      optional :doc, :string, 6, json_name: "doc"
    end
    add_message "google.api.expr.v1alpha1.Reference" do
      optional :name, :string, 1, json_name: "name"
      repeated :overload_id, :string, 3, json_name: "overloadId"
      optional :value, :message, 4, "google.api.expr.v1alpha1.Constant", json_name: "value"
    end
  end
end

module Cerbos::Protobuf::Google
  module Api
    module Expr
      module V1alpha1
        CheckedExpr = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.CheckedExpr").msgclass
        Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Type").msgclass
        Type::ListType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Type.ListType").msgclass
        Type::MapType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Type.MapType").msgclass
        Type::FunctionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Type.FunctionType").msgclass
        Type::AbstractType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Type.AbstractType").msgclass
        Type::PrimitiveType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Type.PrimitiveType").enummodule
        Type::WellKnownType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Type.WellKnownType").enummodule
        Decl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Decl").msgclass
        Decl::IdentDecl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Decl.IdentDecl").msgclass
        Decl::FunctionDecl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Decl.FunctionDecl").msgclass
        Decl::FunctionDecl::Overload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Decl.FunctionDecl.Overload").msgclass
        Reference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.expr.v1alpha1.Reference").msgclass
      end
    end
  end
end
