# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/svc/v1/svc.proto

require 'google/protobuf'

require 'cerbos/protobuf/cerbos/request/v1/request_pb'
require 'cerbos/protobuf/cerbos/response/v1/response_pb'
require 'cerbos/protobuf/google/api/annotations_pb'
require 'cerbos/protobuf/protoc-gen-openapiv2/options/annotations_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cerbos/svc/v1/svc.proto", :syntax => :proto3) do
  end
end

module Cerbos::Protobuf::Cerbos
  module Svc
    module V1
    end
  end
end
