# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/engine/v1/engine.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'cerbos/protobuf/protoc-gen-openapiv2/options/annotations_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cerbos/engine/v1/engine.proto", :syntax => :proto3) do
    add_message "cerbos.engine.v1.PlanResourcesInput" do
    end
    add_message "cerbos.engine.v1.PlanResourcesInput.Resource" do
      optional :kind, :string, 1, json_name: "kind"
      map :attr, :string, :message, 2, "google.protobuf.Value"
      optional :policy_version, :string, 3, json_name: "policyVersion"
      optional :scope, :string, 4, json_name: "scope"
    end
    add_message "cerbos.engine.v1.PlanResourcesFilter" do
      optional :kind, :enum, 1, "cerbos.engine.v1.PlanResourcesFilter.Kind", json_name: "kind"
      optional :condition, :message, 2, "cerbos.engine.v1.PlanResourcesFilter.Expression.Operand", json_name: "condition"
    end
    add_message "cerbos.engine.v1.PlanResourcesFilter.Expression" do
      optional :operator, :string, 1, json_name: "operator"
      repeated :operands, :message, 2, "cerbos.engine.v1.PlanResourcesFilter.Expression.Operand", json_name: "operands"
    end
    add_message "cerbos.engine.v1.PlanResourcesFilter.Expression.Operand" do
      oneof :node do
        optional :value, :message, 1, "google.protobuf.Value", json_name: "value"
        optional :expression, :message, 2, "cerbos.engine.v1.PlanResourcesFilter.Expression", json_name: "expression"
        optional :variable, :string, 3, json_name: "variable"
      end
    end
    add_enum "cerbos.engine.v1.PlanResourcesFilter.Kind" do
      value :KIND_UNSPECIFIED, 0
      value :KIND_ALWAYS_ALLOWED, 1
      value :KIND_ALWAYS_DENIED, 2
      value :KIND_CONDITIONAL, 3
    end
    add_message "cerbos.engine.v1.Resource" do
      optional :kind, :string, 1, json_name: "kind"
      optional :policy_version, :string, 2, json_name: "policyVersion"
      optional :id, :string, 3, json_name: "id"
      map :attr, :string, :message, 4, "google.protobuf.Value"
      optional :scope, :string, 5, json_name: "scope"
    end
    add_message "cerbos.engine.v1.Principal" do
      optional :id, :string, 1, json_name: "id"
      optional :policy_version, :string, 2, json_name: "policyVersion"
      repeated :roles, :string, 3, json_name: "roles"
      map :attr, :string, :message, 4, "google.protobuf.Value"
      optional :scope, :string, 5, json_name: "scope"
    end
  end
end

module Cerbos::Protobuf::Cerbos
  module Engine
    module V1
      PlanResourcesInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.engine.v1.PlanResourcesInput").msgclass
      PlanResourcesInput::Resource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.engine.v1.PlanResourcesInput.Resource").msgclass
      PlanResourcesFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.engine.v1.PlanResourcesFilter").msgclass
      PlanResourcesFilter::Expression = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.engine.v1.PlanResourcesFilter.Expression").msgclass
      PlanResourcesFilter::Expression::Operand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.engine.v1.PlanResourcesFilter.Expression.Operand").msgclass
      PlanResourcesFilter::Kind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.engine.v1.PlanResourcesFilter.Kind").enummodule
      Resource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.engine.v1.Resource").msgclass
      Principal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.engine.v1.Principal").msgclass
    end
  end
end
