# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/annotations.proto

require 'google/protobuf'

require 'cerbos/protobuf/google/api/http_pb'
require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/api/annotations.proto", :syntax => :proto3) do
  end
end

module Cerbos::Protobuf::Google
  module Api
  end
end
