# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/http.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/api/http.proto", :syntax => :proto3) do
    add_message "google.api.HttpRule" do
      optional :selector, :string, 1, json_name: "selector"
      optional :body, :string, 7, json_name: "body"
      optional :response_body, :string, 12, json_name: "responseBody"
      repeated :additional_bindings, :message, 11, "google.api.HttpRule", json_name: "additionalBindings"
      oneof :pattern do
        optional :get, :string, 2, json_name: "get"
        optional :put, :string, 3, json_name: "put"
        optional :post, :string, 4, json_name: "post"
        optional :delete, :string, 5, json_name: "delete"
        optional :patch, :string, 6, json_name: "patch"
        optional :custom, :message, 8, "google.api.CustomHttpPattern", json_name: "custom"
      end
    end
    add_message "google.api.CustomHttpPattern" do
      optional :kind, :string, 1, json_name: "kind"
      optional :path, :string, 2, json_name: "path"
    end
  end
end

module Cerbos::Protobuf::Google
  module Api
    HttpRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.HttpRule").msgclass
    CustomHttpPattern = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.api.CustomHttpPattern").msgclass
  end
end
