# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/audit/v1/audit.proto

require 'google/protobuf'

require 'cerbos/protobuf/buf/validate/validate_pb'
require 'google/protobuf/struct_pb'
require 'cerbos/protobuf/protoc-gen-openapiv2/options/annotations_pb'


descriptor_data = "\n\x1b\x63\x65rbos/audit/v1/audit.proto\x12\x0f\x63\x65rbos.audit.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xae\x03\n\x0eRequestContext\x12\xbc\x01\n\x0b\x61nnotations\x18\x01 \x03(\x0b\x32\x30.cerbos.audit.v1.RequestContext.AnnotationsEntryBh\x92\x41Y2\x1fKey-value pairs of annotations.J3{\"app-name\": \"awesome-app\", \"app-version\": \"1.2.3\"}\xc8\x01\x01\xbaH\t\x9a\x01\x06\"\x04r\x02\x10\x01R\x0b\x61nnotations\x1aV\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueR\x05value:\x02\x38\x01:\x84\x01\x92\x41\x80\x01\n~2|Optional metadata to attach to the request. This information will be captured in the audit logs if audit logging is enabled.Bk\n\x17\x64\x65v.cerbos.api.v1.auditZ:github.com/cerbos/cerbos/api/genpb/cerbos/audit/v1;auditv1\xaa\x02\x13\x43\x65rbos.Api.V1.Auditb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Cerbos::Protobuf::Cerbos
  module Audit
    module V1
      RequestContext = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.audit.v1.RequestContext").msgclass
    end
  end
end
