# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/telemetry/v1/telemetry.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cerbos/telemetry/v1/telemetry.proto", :syntax => :proto3) do
    add_message "cerbos.telemetry.v1.Ping" do
      optional :version, :string, 1, json_name: "version"
      optional :source, :message, 2, "cerbos.telemetry.v1.Ping.Source", json_name: "source"
      optional :features, :message, 3, "cerbos.telemetry.v1.Ping.Features", json_name: "features"
      optional :stats, :message, 4, "cerbos.telemetry.v1.Ping.Stats", json_name: "stats"
    end
    add_message "cerbos.telemetry.v1.Ping.Cerbos" do
      optional :version, :string, 1, json_name: "version"
      optional :commit, :string, 2, json_name: "commit"
      optional :build_date, :string, 3, json_name: "buildDate"
      optional :module_version, :string, 4, json_name: "moduleVersion"
      optional :module_checksum, :string, 5, json_name: "moduleChecksum"
    end
    add_message "cerbos.telemetry.v1.Ping.Source" do
      optional :cerbos, :message, 1, "cerbos.telemetry.v1.Ping.Cerbos", json_name: "cerbos"
      optional :os, :string, 2, json_name: "os"
      optional :arch, :string, 3, json_name: "arch"
      optional :num_cpus, :uint32, 4, json_name: "numCpus"
    end
    add_message "cerbos.telemetry.v1.Ping.Features" do
      optional :audit, :message, 1, "cerbos.telemetry.v1.Ping.Features.Audit", json_name: "audit"
      optional :schema, :message, 2, "cerbos.telemetry.v1.Ping.Features.Schema", json_name: "schema"
      optional :admin_api, :message, 3, "cerbos.telemetry.v1.Ping.Features.AdminApi", json_name: "adminApi"
      optional :storage, :message, 4, "cerbos.telemetry.v1.Ping.Features.Storage", json_name: "storage"
    end
    add_message "cerbos.telemetry.v1.Ping.Features.Audit" do
      optional :enabled, :bool, 1, json_name: "enabled"
      optional :backend, :string, 2, json_name: "backend"
    end
    add_message "cerbos.telemetry.v1.Ping.Features.Schema" do
      optional :enforcement, :string, 1, json_name: "enforcement"
    end
    add_message "cerbos.telemetry.v1.Ping.Features.AdminApi" do
      optional :enabled, :bool, 1, json_name: "enabled"
    end
    add_message "cerbos.telemetry.v1.Ping.Features.Storage" do
      optional :driver, :string, 1, json_name: "driver"
      oneof :store do
        optional :disk, :message, 2, "cerbos.telemetry.v1.Ping.Features.Storage.Disk", json_name: "disk"
        optional :git, :message, 3, "cerbos.telemetry.v1.Ping.Features.Storage.Git", json_name: "git"
        optional :blob, :message, 4, "cerbos.telemetry.v1.Ping.Features.Storage.Blob", json_name: "blob"
      end
    end
    add_message "cerbos.telemetry.v1.Ping.Features.Storage.Disk" do
      optional :watch, :bool, 1, json_name: "watch"
    end
    add_message "cerbos.telemetry.v1.Ping.Features.Storage.Git" do
      optional :protocol, :string, 1, json_name: "protocol"
      optional :auth, :bool, 2, json_name: "auth"
      optional :poll_interval, :message, 3, "google.protobuf.Duration", json_name: "pollInterval"
    end
    add_message "cerbos.telemetry.v1.Ping.Features.Storage.Blob" do
      optional :provider, :string, 1, json_name: "provider"
      optional :poll_interval, :message, 2, "google.protobuf.Duration", json_name: "pollInterval"
    end
    add_message "cerbos.telemetry.v1.Ping.Stats" do
      optional :policy, :message, 1, "cerbos.telemetry.v1.Ping.Stats.Policy", json_name: "policy"
      optional :schema, :message, 2, "cerbos.telemetry.v1.Ping.Stats.Schema", json_name: "schema"
    end
    add_message "cerbos.telemetry.v1.Ping.Stats.Policy" do
      map :count, :string, :uint32, 1
      map :avg_rule_count, :string, :double, 2
      map :avg_condition_count, :string, :double, 3
    end
    add_message "cerbos.telemetry.v1.Ping.Stats.Schema" do
      optional :count, :uint32, 1, json_name: "count"
    end
  end
end

module Cerbos::Protobuf::Cerbos
  module Telemetry
    module V1
      Ping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping").msgclass
      Ping::Cerbos = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Cerbos").msgclass
      Ping::Source = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Source").msgclass
      Ping::Features = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Features").msgclass
      Ping::Features::Audit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Features.Audit").msgclass
      Ping::Features::Schema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Features.Schema").msgclass
      Ping::Features::AdminApi = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Features.AdminApi").msgclass
      Ping::Features::Storage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Features.Storage").msgclass
      Ping::Features::Storage::Disk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Features.Storage.Disk").msgclass
      Ping::Features::Storage::Git = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Features.Storage.Git").msgclass
      Ping::Features::Storage::Blob = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Features.Storage.Blob").msgclass
      Ping::Stats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Stats").msgclass
      Ping::Stats::Policy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Stats.Policy").msgclass
      Ping::Stats::Schema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.telemetry.v1.Ping.Stats.Schema").msgclass
    end
  end
end
