# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/cloud/auth/v1/auth.proto

require 'google/protobuf'

require 'cerbos/protobuf/buf/validate/validate_pb'
require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x1f\x63\x65rbos/cloud/auth/v1/auth.proto\x12\x14\x63\x65rbos.cloud.auth.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n\x0b\x44\x65viceToken\x12*\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x0b\x61\x63\x63\x65ssToken\x12,\n\rrefresh_token\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x0crefreshToken\x12\x41\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\texpiresAt\x12\x1d\n\ntoken_type\x18\x04 \x01(\tR\ttokenTypeB?Z=github.com/cerbos/cloud-api/genpb/cerbos/cloud/auth/v1;authv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Cerbos::Protobuf::Cerbos
  module Cloud
    module Auth
      module V1
        DeviceToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cerbos.cloud.auth.v1.DeviceToken").msgclass
      end
    end
  end
end
