# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cerbos/cloud/apikey/v1/apikey.proto for package 'cerbos.cloud.apikey.v1'
# Original file comments:
# Copyright 2021-2025 Zenauth Ltd.
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'cerbos/protobuf/cerbos/cloud/apikey/v1/apikey_pb'

module Cerbos::Protobuf::Cerbos
  module Cloud
    module Apikey
      module V1
        module ApiKeyService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'cerbos.cloud.apikey.v1.ApiKeyService'

            rpc :IssueAccessToken, ::Cerbos::Protobuf::Cerbos::Cloud::Apikey::V1::IssueAccessTokenRequest, ::Cerbos::Protobuf::Cerbos::Cloud::Apikey::V1::IssueAccessTokenResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
